FEATURES: 
  - Loan_ID
  - Gender
  - Married
  - Dependents
  - Education
  - Self_Employed
  - ApplicantIncome
  - CoapplicantIncome
  - LoanAmount
  - Loan_Amount_Term
  - Credit_History
  - Property_Area
  - Loan_Status

NUMERIC_FEATURES : 
  - ApplicantIncome
  - LoanAmount
  - Loan_Amount_Term

CATEGORICAL_FEATURES: 
  - Gender
  - Married
  - Dependents
  - Education
  - Self_Employed
  - Credit_History
  - Property_Area

FEATURE_TO_MODIFY: 
  - ApplicantIncome

FEATURE_TO_ADD: 
  - CoapplicantIncome

DROP_FEATURES: 
  - CoapplicantIncome

LOG_FEATURES :
  - ApplicantIncome 
  - LoanAmount

TARGET: 
  - Loan_Status