artifacts_root: artifacts 

data_ingestion:
    root_dir : artifacts/data_ingestion
    test_data_url: 'https://github.com/HarishKumarSedu/Packaging_model_Baseclasses/raw/main/data/test.zip' 
    train_data_url: 'https://github.com/HarishKumarSedu/Packaging_model_Baseclasses/raw/main/data/train.zip' 
    test_unzip_dir: artifacts/data_ingestion/test.zip
    train_unzip_dir: artifacts/data_ingestion/train.zip
    local_data_path : artifacts/data_ingestion 
